
import styles from './styles.module.css'
import '../styles/global.css'
import { Inter, Roboto_Mono } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
});

export const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {

 
  return (
    <html lang="tr" className={roboto_mono.className}>
      <body className={styles.container}>
        <header><h2>Başlık Kısmı</h2></header>
        {children}
        <footer><h3>Footer Kısmı</h3></footer>
        </body>
    </html>
  )
}
