
import styles from './styles.module.css'
import '../styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={styles.container}>
        <header><h2>Başlık Kısmı</h2></header>
        {children}
        <footer><h3>Footer Kısmı</h3></footer>
        </body>
    </html>
  )
}
