

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>BAŞLIK KISMI</header>
        {children}
        <footer>ALT KISIM</footer>
        </body>
    </html>
  )
}
